#!/usr/bin/env bash
set -e

if [[ -z "$SRCS" ]]; then
  echo "The variable 'SRCS' is not defined."
  exit 1
fi

# Source common without doing any bootstrap work at this stage
# Bootstrapping should be done inside the build container
determine_cri_bin() {
    if [ "${KUBEVIRT_CRI}" = "podman" ]; then
        echo podman
    elif [ "${KUBEVIRT_CRI}" = "docker" ]; then
        echo docker
    else
        if podman ps >/dev/null 2>&1; then
            echo podman
        elif docker ps >/dev/null 2>&1; then
            echo docker
        else
            echo ""
        fi
    fi
}

fail_if_cri_bin_missing() {
    if [ -z "${KUBEVIRT_CRI}" ]; then
        echo >&2 "no working container runtime found. Neither docker nor podman seems to work."
        exit 1
    fi
}

KUBEVIRT_CRI=$(determine_cri_bin)
fail_if_cri_bin_missing

default_BUILDER_IMAGE="libvirt-build-image"

BUILDER_IMAGE=${BUILDER_IMAGE:-"${default_BUILDER_IMAGE}"}

BUILDER=${BUILDER:-custom-rpms}

# Create the persistent container volume
if [ -z "$($KUBEVIRT_CRI volume list | grep ${BUILDER})" ]; then
    $KUBEVIRT_CRI volume create ${BUILDER}
fi

selinux_bind_options=",z"
# Using Podman and MacOS and 'z' bind option may not work correctly.
# See: https://github.com/containers/podman/issues/13631
if [[ $KUBEVIRT_CRI = podman* ]] && [[ "$(uname -s)" == "Darwin" ]]; then
    selinux_bind_options=""
fi

IFS="," read -r -a array <<< "$SRCS"


# Make sure that the output directory exists on both sides
if [[ ! -z "$OUT_DIR" ]]; then
    OUT_DIR_SRC=$(echo "$OUT_DIR" | cut -d ":" -f 1)
    OUT_DIR_DST=$(echo "$OUT_DIR" | cut -d ":" -f 2)
    $KUBEVIRT_CRI run -v "${BUILDER}:/root:rw${selinux_bind_options}" --security-opt "label=disable" --rm ${BUILDER_IMAGE} mkdir -p /root/${OUT_DIR_SRC}
    mkdir -p ${OUT_DIR_DST}
fi

# Start an rsyncd instance and make sure it gets stopped after the script exits
RSYNC_CID=$($KUBEVIRT_CRI run -d -v "${BUILDER}:/root:rw${selinux_bind_options}" --security-opt "label=disable" --cap-add SYS_CHROOT --expose 873 -P ${BUILDER_IMAGE} /usr/bin/rsync --no-detach --daemon --verbose)

function finish() {
    $KUBEVIRT_CRI stop --time 1 ${RSYNC_CID} >/dev/null 2>&1
    $KUBEVIRT_CRI rm -f ${RSYNC_CID} >/dev/null 2>&1
}
trap finish EXIT

RSYNCD_PORT=$($KUBEVIRT_CRI port $RSYNC_CID 873 | cut -d':' -f2)

rsynch_fail_count=0

while ! rsync ${KUBEVIRT_DIR}/${RSYNCTEMP} "rsync://root@127.0.0.1:${RSYNCD_PORT}/build/${RSYNCTEMP}" &>/dev/null; do
    if [[ "$rsynch_fail_count" -eq 0 ]]; then
        printf "Waiting for rsyncd to be ready"
        sleep .1
    elif [[ "$rsynch_fail_count" -lt 30 ]]; then
        printf "."
        sleep 1
    else
        printf "failed"
        exit 1
    fi
    rsynch_fail_count=$((rsynch_fail_count + 1))
done

printf "\n"

rsynch_fail_count=0

_rsync() {
    # Preserve permissions, but change ownership to destination
    rsync -rlpt "$@"
}

IFS="," read -r -a sources <<< "$SRCS"

for item in "${sources[@]}"; do
    if [[ ! -z "$item" ]]; then
        # Copy source into the persistent container volume
        _rsync \
            --delete \
            $item \
            "rsync://root@127.0.0.1:${RSYNCD_PORT}/build/"
    fi
done

volumes="${EXTRA_VOLS}"

# Add build volume mount (directory root for source in the container)
volumes="$volumes -v ${BUILDER}:/build:rw${selinux_bind_options}"

# append .docker secrets directory as volume
mkdir -p "${HOME}/.docker/secrets"
volumes="$volumes -v ${HOME}/.docker/secrets:/root/.docker/secrets:ro${selinux_bind_options}"

# Use a bind-mount to expose docker/podman auth file to the container
if [[ $KUBEVIRT_CRI = podman* ]] && [[ -f "${XDG_RUNTIME_DIR}/containers/auth.json" ]]; then
    volumes="$volumes --mount type=bind,source=${XDG_RUNTIME_DIR}/containers/auth.json,target=/root/.docker/config.json,readonly"
elif [[ -f "${HOME}/.docker/config.json" && "$(cat ${HOME}/.docker/config.json | jq 'has("credHelpers")')" != "true" ]]; then
    volumes="$volumes --mount type=bind,source=${HOME}/.docker/config.json,target=/root/.docker/config.json,readonly"
fi

# add custom docker certs, if needed
if [ -n "$DOCKER_CA_CERT_FILE" ] && [ -f "$DOCKER_CA_CERT_FILE" ]; then
    volumes="$volumes -v ${DOCKER_CA_CERT_FILE}:${DOCKERIZED_CUSTOM_CA_PATH}:ro${selinux_bind_options}"
fi

BUILD_CID=$($KUBEVIRT_CRI run -dit ${volumes} -w /build ${BUILDER_IMAGE})
function finish() {
    $KUBEVIRT_CRI stop --time 1 ${RSYNC_CID} >/dev/null 2>&1
    $KUBEVIRT_CRI rm -f ${RSYNC_CID} >/dev/null 2>&1
    $KUBEVIRT_CRI stop --time 1 ${BUILD_CID} >/dev/null 2>&1
    $KUBEVIRT_CRI rm -f ${BUILD_CID} >/dev/null 2>&1
}

function copy_out() {
    if [[ ! -z "$OUT_DIR" ]]; then
        echo "Copying output to ${OUT_DIR_DST}"
        _rsync --delete "rsync://root@127.0.0.1:${RSYNCD_PORT}/build/${OUT_DIR_SRC}/" ${OUT_DIR_DST}
    fi
}

# Run the command
test -t 1 && USE_TTY="-t"
if ! $KUBEVIRT_CRI exec ${CONTAINER_ENV} ${USE_TTY} ${BUILD_CID} $1; then
    # Copy the build output out of the container, make sure that _out exactly matches the build result
    copy_out
    exit 1
fi

copy_out