#!/usr/bin/env bash
set -e

if [[ -z "$LIBVIRT_DIR" ]]; then
  echo "The variable 'LIBVIRT_DIR' is not defined."
  exit 1
fi


# Source common without doing any bootstrap work at this stage
# Bootstrapping should be done inside the build container
determine_cri_bin() {
    if [ "${KUBEVIRT_CRI}" = "podman" ]; then
        echo podman
    elif [ "${KUBEVIRT_CRI}" = "docker" ]; then
        echo docker
    else
        if podman ps >/dev/null 2>&1; then
            echo podman
        elif docker ps >/dev/null 2>&1; then
            echo docker
        else
            echo ""
        fi
    fi
}

fail_if_cri_bin_missing() {
    if [ -z "${KUBEVIRT_CRI}" ]; then
        echo >&2 "no working container runtime found. Neither docker nor podman seems to work."
        exit 1
    fi
}

KUBEVIRT_CRI=$(determine_cri_bin)
fail_if_cri_bin_missing

default_LIBVIRT_BUILDER_IMAGE="registry.gitlab.com/libvirt/libvirt/ci-centos-stream-10"

LIBVIRT_BUILDER_IMAGE=${LIBVIRT_BUILDER_IMAGE:-"${default_LIBVIRT_BUILDER_IMAGE}"}

OUT_DIR=${OUT_DIR:-${LIBVIRT_DIR}/build}

SYNC_OUT=${SYNC_OUT:-true}

BUILDER=${job_prefix:-libvirt}

SYNC_VENDOR=${SYNC_VENDOR:-false}

CONTAINER_ENV="--env HTTP_PROXY=${HTTP_PROXY} --env HTTPS_PROXY=${HTTP_PROXY} --env NO_PROXY=${NO_PROXY}"

# Create the persistent container volume
if [ -z "$($KUBEVIRT_CRI volume list | grep ${BUILDER})" ]; then
    $KUBEVIRT_CRI volume create ${BUILDER}
fi

selinux_bind_options=",z"
# Using Podman and MacOS and 'z' bind option may not work correctly.
# See: https://github.com/containers/podman/issues/13631
if [[ $KUBEVIRT_CRI = podman* ]] && [[ "$(uname -s)" == "Darwin" ]]; then
    selinux_bind_options=""
fi


# Make sure that the output directory exists on both sides
$KUBEVIRT_CRI run ${CONTAINER_ENV} -v "${BUILDER}:/root:rw${selinux_bind_options}" --security-opt "label=disable" --rm ${LIBVIRT_BUILDER_IMAGE} mkdir -p /root/libvirt/build
mkdir -p ${OUT_DIR}

# Start an rsyncd instance and make sure it gets stopped after the script exits
RSYNC_CID=$($KUBEVIRT_CRI run ${CONTAINER_ENV} -d -v "${BUILDER}:/root:rw${selinux_bind_options}" --security-opt "label=disable" --cap-add SYS_CHROOT --expose 873 -P ${LIBVIRT_BUILDER_IMAGE} /usr/bin/rsync --no-detach --daemon --verbose)

function finish() {
    $KUBEVIRT_CRI stop --time 1 ${RSYNC_CID} >/dev/null 2>&1
    $KUBEVIRT_CRI rm -f ${RSYNC_CID} >/dev/null 2>&1
}
trap finish EXIT

RSYNCD_PORT=$($KUBEVIRT_CRI port $RSYNC_CID 873 | cut -d':' -f2)

rsynch_fail_count=0

while ! rsync ${KUBEVIRT_DIR}/${RSYNCTEMP} "rsync://root@127.0.0.1:${RSYNCD_PORT}/build/${RSYNCTEMP}" &>/dev/null; do
    if [[ "$rsynch_fail_count" -eq 0 ]]; then
        printf "Waiting for rsyncd to be ready"
        sleep .1
    elif [[ "$rsynch_fail_count" -lt 30 ]]; then
        printf "."
        sleep 1
    else
        printf "failed"
        exit 1
    fi
    rsynch_fail_count=$((rsynch_fail_count + 1))
done

printf "\n"

rsynch_fail_count=0

_rsync() {
    # Preserve permissions, but change ownership to destination
    rsync -rlpt "$@"
}

# Copy libvirt into the persistent container volume
_rsync \
    --delete \
    ${LIBVIRT_DIR}/ \
    "rsync://root@127.0.0.1:${RSYNCD_PORT}/build/libvirt"

# Copy libvirt build script
_rsync \
    ${LIBVIRT_BUILD_SCRIPT} \
    "rsync://root@127.0.0.1:${RSYNCD_PORT}/build/"


volumes="${EXTRA_VOLS}"
volumes="$volumes -v ${BUILDER}:/build:rw${selinux_bind_options}"

# append .docker secrets directory as volume
mkdir -p "${HOME}/.docker/secrets"
volumes="$volumes -v ${HOME}/.docker/secrets:/root/.docker/secrets:ro${selinux_bind_options}"

# Use a bind-mount to expose docker/podman auth file to the container
if [[ $KUBEVIRT_CRI = podman* ]] && [[ -f "${XDG_RUNTIME_DIR}/containers/auth.json" ]]; then
    volumes="$volumes --mount type=bind,source=${XDG_RUNTIME_DIR}/containers/auth.json,target=/root/.docker/config.json,readonly"
elif [[ -f "${HOME}/.docker/config.json" && "$(cat ${HOME}/.docker/config.json | jq 'has("credHelpers")')" != "true" ]]; then
    volumes="$volumes --mount type=bind,source=${HOME}/.docker/config.json,target=/root/.docker/config.json,readonly"
fi

# add custom docker certs, if needed
if [ -n "$DOCKER_CA_CERT_FILE" ] && [ -f "$DOCKER_CA_CERT_FILE" ]; then
    volumes="$volumes -v ${DOCKER_CA_CERT_FILE}:${DOCKERIZED_CUSTOM_CA_PATH}:ro${selinux_bind_options}"
fi

# if defined, append the ARTIFACTS directory
if [ -n "$ARTIFACTS" ]; then
    mkdir -p "$ARTIFACTS"
    if [[ "$ARTIFACTS" = /* ]]; then
        volumes="$volumes -v ${ARTIFACTS}:${ARTIFACTS}:rw${selinux_bind_options}"
    else
        echo "ARTIFACTS directory is specified, but it is not an absolute directory"
        exit 1
    fi
fi

BUILD_CID=$($KUBEVIRT_CRI run -dit ${volumes} -w /build ${LIBVIRT_BUILDER_IMAGE})
function finish() {
    $KUBEVIRT_CRI stop --time 1 ${RSYNC_CID} >/dev/null 2>&1
    $KUBEVIRT_CRI rm -f ${RSYNC_CID} >/dev/null 2>&1
    $KUBEVIRT_CRI stop --time 1 ${BUILD_CID} >/dev/null 2>&1
    $KUBEVIRT_CRI rm -f ${BUILD_CID} >/dev/null 2>&1
}

# Run the command
test -t 1 && USE_TTY="-t"
if ! $KUBEVIRT_CRI exec ${CONTAINER_ENV} ${USE_TTY} ${BUILD_CID} $1; then
    # Copy the build output out of the container, make sure that _out exactly matches the build result
    if [ "$SYNC_OUT" = "true" ]; then
        _rsync --delete "rsync://root@127.0.0.1:${RSYNCD_PORT}/build/libvirt/build/" ${OUT_DIR}
    fi
    exit 1
fi

if [ "$SYNC_OUT" = "true" ]; then
    _rsync --delete "rsync://root@127.0.0.1:${RSYNCD_PORT}/build/libvirt/build/" ${OUT_DIR}
fi